# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed6dc1601f7b00e6942f7240a47a4da86d27b614944848aea703403392d0d1712138eab6edcffadf4ba260b55b0d60a0525d7c9847485f2841ab863fd1551838

test:
  secret_key_base: 0995eed5294aeb4f0d8e97acf236e53dbe2472314640d1c2eb31ac540896aa03ea593aa0c150eea9b1ae250dd6454f707e43205cffeb74002d73d2cb7143afe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
